import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/layouts/Header'
import Footer from '@/layouts/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className + ' overflow-x-hidden'}>
        <Header />
        <div className='pt-[64px] 2xl:pt-[80px]'>{children}</div>
        <Footer />
      </body>
    </html>
  )
}
